---
# Reminder, aws creds must be set or it will use the default group in .aws file.
- name: Deploy monolithGrafaws cloudformation
  cloudformation:
    stack_name: "{{ stack_name }}-cloudformation"
    state: "{{ target_state }}"
    aws_access_key: "{{ target_aws_access_key }}"
    aws_secret_key: "{{ target_aws_secret_key }}"
    region: "{{ target_region }}"
    disable_rollback: false
    template: roles/monolithGrafaws_aws_environment/files/aws_cloudformation.yml
    template_parameters:
      DomainName: "{{ domain_name }}"
      EnvironmentName: "{{ stack_name }}"
      HomeIPAddress: "{{ localhost_external_ip_address }}/32"
      KeyName: "{{ ec2_ssh_key_name }}"
    tags:
      Stack: "{{ stack_name }}-cloudformation"
  register: cloutformation_deploy_output

- name: Find and Set EIP address
  set_fact:
    eip_address: "{{item.physical_resource_id}}"
  when: target_state == "present"
            and item.logical_resource_id == "EIP"
  loop: "{{ cloutformation_deploy_output.stack_resources }}"

- name: Add host to group 'just_created'
  add_host:
    name: '{{ eip_address }}'
    groups: just_created
  when: target_state == "present"
