---

- name: Update repo cache and install postgres
  apt:
    update_cache: yes
    pkg:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Add postgres user
  user:
    name: postgres
    shell: /bin/bash
    createhome: "True"
    skeleton: "True"
    state: present

- name: set authorized keys
  authorized_key:
    user: postgres
    state: present
    key: "{{ hostvars['localhost']['postgres_user_public_key'] }}"

- name: start the server
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Set Listen Addresses
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: '^#listen_addresses = '
    insertafter: '^#listen_addresses = '
    line: listen_addresses = '*'
  notify: Restart postgres

- name: Set pg_hba.conf
  lineinfile:
    path: /etc/postgresql/12/main/pg_hba.conf
    insertafter: '^# IPv4 local connections:'
    line: host    all             all             0.0.0.0/0               md5
  notify: Restart postgres
