---
# Grafaws Monolith Deployment

- name: Monolith Grafaws Cloudformation
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  vars:
      target_state: present
      target_region: us-west-2
  roles:
    - set_playbook_facts
    - monolithGrafaws_aws_environment

- name: Monolith Grafaws Configure EC2
  hosts: just_created
  remote_user: ubuntu
  gather_facts: false
  become: yes
  vars:
    target_state: "{{ hostvars['localhost']['target_state'] }}"
  roles:
    - role: install_nginx # includes certbot
      when: target_state == 'present'
    - role: install_postgres
      when: target_state == 'present'
    - role: install_grafana
      when: target_state == 'present'

- name: Configure grafana
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  vars:
      target_state: "{{ hostvars['localhost']['target_state'] }}"
  roles:
    - role: configure_grafana_data_source
      when: target_state == 'present'

- name: Configure Postgres
  hosts: just_created
  remote_user: postgres
  gather_facts: false
  become: false
  vars:
    postgres_database_host: "{{ ec2_ip_address }}"
    target_state: "{{ hostvars['localhost']['target_state'] }}"
  roles:
    - role: configure_database
      when: target_state == 'present'

- name: Postgres Tables
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  vars:
    target_state: "{{ hostvars['localhost']['target_state'] }}"
  roles:
    - role: construct_tables
      when: target_state == 'present'

- name: Build python project
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  roles:
    - role: build_grafaws_monolith

- name: Deploy python project
  hosts: just_created
  remote_user: ubuntu
  gather_facts: false
  become: no
  vars:
    target_state: "{{ hostvars['localhost']['target_state'] }}"
  roles:
    - role: deploy_python_code
      when: target_state == 'present'

# not implemented
# - name: Add panels to grafana
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: no
#   vars:
#     target_state: "{{ hostvars['localhost']['target_state'] }}"
#   roles:
#     - role: add_grafana_panels
#       when: target_state == 'present'
