---
# Grafaws Monolith Deployment

# TODO add more conditionals to plays absent/present
# TODO see if we can use delegate_to: to specify which host performs a task instead of swithing hosts

- name: Monolith Grafaws Cloudformation
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  vars:
      stack_name: monolithGrafaws
      target_state: present
      target_region: us-west-2

  roles:
    - set_playbook_facts
    - monolithGrafaws_aws_environment

- name: Monolith Grafaws Configure EC2
  hosts: just_created
  remote_user: ubuntu
  gather_facts: false
  become: yes
  vars:
    target_state: "{{ hostvars['localhost']['target_state'] }}"
    stack_name: "{{ hostvars['localhost']['stack_name'] }}"
    grafana_user_public_key: "{{ hostvars['localhost']['ssh_key_name'] }}"

  roles:

    # TODO move upgrade to earlier, add autoclean and autoremove
    # TODO some kind of OS maintenance play 

    # TODO distinguish between provision and configure

    - role: install_nginx # includes certbot
      when: target_state == 'present'
    - role: install_postgres
      when: target_state == 'present'
    - role: install_grafana
      when: target_state == 'present'

- name: configure grafana
  hosts: localhost
  connection: local
  gather_facts: false
  become: no

  roles:
    - role: configure_grafana_data_source
      when: target_state == 'present'

- name: Configure Postgres
  hosts: just_created
  remote_user: postgres
  gather_facts: false
  become: false
  vars:
    postgres_database_host: "{{ ec2_ip_address }}"
  roles:
    - role: configure_database

- name: Postgres Tables
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  roles:
    - role: construct_tables

- name: build python project
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  roles:
    - role: build_grafaws_monolith

- name: Deploy python project
  hosts: just_created
  remote_user: ubuntu
  gather_facts: false
  roles:
    - role: deploy_python_code

- name: Add panels to grafana
  hosts: localhost
  connection: local
  gather_facts: false
  become: no
  roles:
    - role: add_grafana_panels
      when: target_state == 'present'
