---

- name: Get localhost external ip address
  ipify_facts:
  register: external_ip_address

- name: Set localhost_external_ip_address for playbook
  set_fact:
    cacheable: yes
    localhost_external_ip_address: "{{ external_ip_address.ansible_facts.ipify_public_ip }}"

- name: Set certbot_email_address for playbook
  set_fact:
    cacheable: yes
    certbot_email_address: "{{ lookup('ini', 'certbot_email_address section=secrets file=./secrets.ini') }}"

- name: Set target_state for playbook
  set_fact:
    cacheable: yes
    target_state: "{{ target_state }}"

- name: Set DNS and stack name for playbook
  set_fact:
    cacheable: yes
    stack_name: "{{ lookup('ini', 'subdomain_name section=configuration file=./secrets.ini') }}"
    domain_name: "{{ lookup('ini', 'domain_name section=configuration file=./secrets.ini') }}"

- name: Set aws creds for playbook
  set_fact:
    cacheable: yes
    target_aws_access_key: "{{ lookup('ini', 'aws_access_key_id section=paul-private file=~/.aws/credentials') }}"
    target_aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section=paul-private file=~/.aws/credentials') }}"

- name: Set postgres user creds for playbook
  set_fact:
    cacheable: yes
    postgres_grafana_user_username: "{{ lookup('ini', 'postgres_grafana_user_username section=secrets file=./secrets.ini') }}"
    postgres_grafana_user_password: "{{ lookup('ini', 'postgres_grafana_user_password section=secrets file=./secrets.ini') }}"
    postgres_remote_admin_username: "{{ lookup('ini', 'postgres_remote_admin_username section=secrets file=./secrets.ini') }}"
    postgres_remote_admin_password: "{{ lookup('ini', 'postgres_remote_admin_password section=secrets file=./secrets.ini') }}"
    postgres_python_user_username: "{{ lookup('ini', 'postgres_python_user_username section=secrets file=./secrets.ini') }}"
    postgres_python_user_password: "{{ lookup('ini', 'postgres_python_user_password section=secrets file=./secrets.ini') }}"
    postgres_user_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/paulHome.pub') }}"

- name: Set postgres database info for playbook
  set_fact:
    cacheable: yes
    postgres_database_name: "{{ lookup('ini', 'postgres_database_name section=secrets file=./secrets.ini') }}"
    postgres_schema_name: "{{ lookup('ini', 'postgres_schema_name section=secrets file=./secrets.ini') }}"
    postgres_database_port: "{{ lookup('ini', 'postgres_database_port section=secrets file=./secrets.ini') }}"

- name: Set ec2_ssh_key_name for playbook
  set_fact:
    cacheable: yes
    ec2_ssh_key_name: "{{ lookup('ini', 'ec2_ssh_key_name section=secrets file=./secrets.ini') }}"

- name: Set weather api APP_ID for playbook
  set_fact:
    cacheable: yes
    APP_ID: "{{ lookup('ini', 'APP_ID section=secrets file=./secrets.ini') }}"

- name: Set grafana installation admin credentials
  set_fact:
    cacheable: yes
    grafana_admin_username: "{{ lookup('ini', 'grafana_admin_username section=secrets file=./secrets.ini') }}"
    grafana_admin_password: "{{ lookup('ini', 'grafana_admin_password section=secrets file=./secrets.ini') }}"
