--- 

- name: Add gpg key for grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Update repo cache and install dependencies
  apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Install grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Change default admin user
  ini_file:
    path: /etc/grafana/grafana.ini
    section: security
    option: admin_user
    value:  "{{ hostvars['localhost']['grafana_admin_username'] }}"
  notify: Restart postgres

- name: Change default admin password
  ini_file:
    path: /etc/grafana/grafana.ini
    section: security
    option: admin_password
    value:  "{{ hostvars['localhost']['grafana_admin_password'] }}"
  notify: Restart postgres

- name: start the server
  service:
    name: grafana-server
    state: started
    enabled: yes
